language: racket

env:
 - RACKET_VERSION=HEAD

before_install:
 - git clone https://github.com/greghendershott/travis-racket.git
 - cat travis-racket/install-racket.sh | bash

install:

before_script:

script:
 - /usr/racket/bin/raco make main.rkt
 - cd test
 - /usr/racket/bin/raco test main.rkt -x main.rkt

after_script: