language: racket

env:
 - RACKET_VERSION=HEAD

before_install:
 - git clone https://github.com/greghendershott/travis-racket.git
 - cat travis-racket/install-racket.sh | bash
 # TODO I feel so bad doing this. Need to work out a way to waste their bandwidth less
 # Install latest Git to avoid problem with cloning Z3
 - git clone https://github.com/git/git.git
 - sudo apt-get install gettext zlib1g-dev asciidoc libcurl4-openssl-dev
 - cd git
 - make configure
 - ./configure --prefix=/usr
 - make all doc
 - sudo make install
 # Install Z3
 - git clone https://git01.codeplex.com/z3
 - cd z3
 - mkdir ~/my-z3
 - python scripts/mk_make.py --prefix=~/my-z3
 - cd build
 - make
 - make install
 - export PATH=$HOME/my-z3:$PATH

install:

before_script:

script:
 - /usr/racket/bin/raco pkg install
 - cd test
 - /usr/racket/bin/raco test -x main.rkt

after_script: