language: racket

env:
 - RACKET_VERSION=HEAD

before_install:
 - git clone https://github.com/greghendershott/travis-racket.git
 - cat travis-racket/install-racket.sh | bash
 # TODO I feel so bad doing this. Need to work out a way to waste their bandwidth less
 # Install latest Git to avoid problem with cloning Z3
 - git clone https://github.com/git/git.git
 - sudo apt-get install gettext zlib1g-dev asciidoc libcurl4-openssl-dev
 - cd git
 - make configure
 - ./configure --prefix=/usr
 - make all
 - sudo make install
 - cd ..
 # Install Z3
 - git clone https://github.com/Z3Prover/z3.git
 - cd z3
 - git checkout tags/z3-4.4.1  # until I figure out what's wrong...
 - python scripts/mk_make.py
 - cd build
 - make
 - sudo make install
 - cd ../..

install:

before_script:

script:
 # Set up Z3 path
 - ls /usr/lib/python2.7/dist-packages
 - ls /opt/python/2.7.14/lib
 - export Z3_LIB="/opt/python/2.7.14/lib"
 # Install soft-contract
 - cd soft-contract
 - /usr/racket/bin/raco pkg install --deps search-auto
 # Run test suite
 - /usr/racket/bin/raco test test/sanity-test.rkt

after_script: